FROM emqx/emqx:4.3.17
LABEL maintainer=caolei19@tal.com
LABEL version=1.0
LABEL description=emqx-dev

COPY etc/acl.conf /opt/emqx/etc/acl.conf
COPY etc/emqx.conf /opt/emqx/etc/emqx.conf
COPY etc/plugins/emqx_auth_http.conf /opt/emqx/etc/plugins/emqx_auth_http.conf