server:
  port: 8787
spring:
  application:
    name: DrPanda-Lighthouse
  datasource:
    #    url: jdbc:mysql://rm-bp1qz4b7e260219h5.mysql.rds.aliyuncs.com:3306/dp-lighthouse?useUnicode=true?characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    #    username: dppad2
    #    password: s$gQr0MJvuLA7#@H
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lighthouse?useUnicode=true?characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver